name: Validate Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-commits:
    name: Validate Commit Messages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate conventional commits
        uses: amannn/action-semantic-pull-request@v4
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
          subjectPattern: ^[a-z].*[^.]$
          subjectPatternError: |
            The subject "{subject}" in the PR title "{title}" didn't match the configured pattern. Please ensure that the subject is lowercased and doesn't end with a period.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
